version: '3.7'
services:
  web:
    tty: true
    stdin_open: true
    container_name: web
    entrypoint: "./docker-entrypoint.sh"
    command: ash -c "bundle exec rails server -p 3000 -b 0.0.0.0"
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle:cached
    networks:
      - web-net

networks:
  web-net:
    name: web-net

volumes:
  bundle:
    name: web-bundle
  # postgres-data:
  #   name: postgres-data